---
- name: Reboot for revert
  ansible.builtin.reboot:
    reboot_timeout: 7200

- name: Wait for snaps to merge
  ansible.builtin.shell: lvs | grep pre_upgrade_ | wc -l
  register: snap_merge_status
  until: snap_merge_status.stdout == '0'
  changed_when: false
  retries: 60
  delay: 10

- name: Gather updated facts
  ansible.builtin.setup:

- name: Get snapmgt.bash status
  ansible.builtin.include_tasks: tasks/snapmgt_bash_status.yml
...